#!/usr/bin/env python3

import argparse
import logging
import os.path

from rocrate.rocrate import ROCrate

from ingestion_pipeline.provenance import (
    ProvenanceDocstring,
    ProvenanceLog,
    WorkflowBuilder,
)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(filename)s::%(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


def parse_args():
    """Parse input parameters provided at runtime."""
    parser = argparse.ArgumentParser(
        description="Generate a RO-Crate for an ingestion pipeline run."
    )
    parser.add_argument(
        "--logfile-prov-path",
        type=str,
        required=True,
        help="Path to the provenance log in JSON format generated by the ingestion pipeline.",
    )
    parser.add_argument(
        "--main-class-path",
        type=str,
        required=True,
        help=(
            "Path to the main class of the ingestion pipeline to extract docstrings from. "
        ),
    )
    parser.add_argument(
        "--docstring-convention",
        type=str,
        required=True,
        help=("Docstring convention used in the main class. Default is 'numpy'."),
        default="numpy",
    )
    parser.add_argument(
        "--request-id",
        type=str,
        required=False,
        help=(
            "Request ID to filter the provenance logs. If not provided, "
            "the last request ID in the log file will be used."
        ),
    )
    parser.add_argument(
        "--output-crate-path",
        type=str,
        required=False,
        help="Path to save the generated RO-Crate. Default is 'ingestion_pipeline_run_crate'.",
        default="ingestion_pipeline_run_crate",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug logging output.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)
    else:
        logging.getLogger().setLevel(logging.INFO)

    if not args.logfile_prov_path:
        raise ValueError(
            "You must provide a path to the provenance log file through the --logfile-prov argument."
        )

    # Provenance log instance
    prov_log = ProvenanceLog(
        args.logfile_prov_path,
        request_id=args.request_id,
        # output_types=["downloaded_files", "homogenized_files", "aggregated_files"],
    )
    logger.debug(f"Loaded provenance log from: {args.logfile_prov_path}")
    logger.debug(
        f"Provenance log contains {len(prov_log.logs)} entries for request_id: "
        f"{args.request_id if args.request_id else 'last in log file'}"
    )

    # Create the RO-Crate and builder
    crate = ROCrate()
    crate.license = "https://spdx.org/licenses/Apache-2.0.html"
    crate.name = "ERA5 Ingestion Pipeline Crate"
    crate.description = (
        "A crate containing the provenance of the ERA ingestion pipeline runs "
        "(tas, tasmax, tasmin, pr, sfcWind)."
    )
    builder = WorkflowBuilder(
        crate, name=prov_log.workflow_file, path=prov_log.workflow_file
    )
    logger.debug("Created new RO-Crate and WorkflowBuilder instances")

    # Add workflow script to the crate
    logger.debug("Adding workflow script to the crate")
    builder.lang = {
        "@id": "#python",
        "name": "Python",
        "url": "https://www.python.org/",
        "version": prov_log.programming_language,
    }
    builder.workflow = {
        "name": "Download ERA5 Ingestion Pipeline",
        "description": "Ingestion pipeline script to download ERA5 dataset.",
        "encodingFormat": "text/x-python",
        "contentSize": os.path.getsize(prov_log.workflow_file),
    }
    workflow_crate = builder.workflow
    logger.info(f"Added workflow entity to the crate: {workflow_crate}")

    # Add input parameters extracting them from docstrings
    prov_docs = ProvenanceDocstring(
        class_path=args.main_class_path,
        docstring_convention=args.docstring_convention,
    )
    logger.debug(
        f"Extracting input parameters from the constructor docstring of class at path: {args.main_class_path}"
    )
    logger.debug(f"Using docstring convention: {args.docstring_convention}")
    workflow_crate["input"] = []
    for name, description in prov_docs.parameters:
        builder.input = {
            "name": name,
            "description": description,
        }
        input_param = builder.input
        workflow_crate.append_to("input", {"@id": input_param["@id"]})
    logger.info(
        f"Added {len(list(prov_docs.parameters))} input parameters gathered from the "
        f"{args.main_class_path} constructor docstring"
    )
    logger.debug(
        f"Input parameters added to the crate workflow: {workflow_crate['input']}"
    )

    # Add CreateAction to describe the execution of the workflow
    logger.debug("Adding CreateAction entities for workflow execution")
    actions = prov_log.actions
    logger.info(f"Found {len(actions)} actions in the provenance log: {actions}")
    for action_id, action_entry_list in actions.items():
        # Add base metadata for the action
        logger.debug(
            f"Processing action_id: {action_id} with entries: {action_entry_list}"
        )
        action_entry_create = prov_log.get_entries_for_key(
            key_name="message",
            action="/create",
            whole_entry=True,
            entry_list=action_entry_list,
        )
        action_entry_create = action_entry_create[0]  # SHOULD BE ONLY ONE
        logger.debug(f"Retrieved action=/create entry: {action_entry_create}")
        action_name = action_entry_create.get("message", "unknown-action-name")
        logger.debug(
            f"Assign action name as the message found in action=/create entry: {action_name}"
        )
        builder.action = {
            "@id": action_id,
            "name": action_name,
            "instrument": workflow_crate,
            "startTime": action_entry_create.get("timestamp", "unknown-start-time"),
        }
        # Add the action to the builder
        action = builder.action
        logger.debug(
            f"Added CreateAction entity with base metadata to the crate: {action}"
        )
        # Add input values for the action
        action_entry_input = prov_log.get_entries_for_key(
            key_name="input_args", action="/input", entry_list=action_entry_list
        )
        for input_args in action_entry_input:
            for key, value in input_args.items():
                builder.input = {"name": key}
                input_param = builder.input
                builder.input_value = {
                    "name": key,
                    "value": str(value),
                }
                input_value = builder.input_value
                input_value.append_to("exampleOfWork", {"@id": input_param["@id"]})
                logger.debug(
                    f"Adding input parameter with @id '{input_param['@id']}' and value "
                    f"'{value}' for the action '{action_id}'"
                )
                action.append_to("object", {"@id": input_value["@id"]})
                logger.debug(
                    f"Appended input value with @id '{input_value['@id']}' to the action's object property"
                )
        logger.info(
            f"Added {len(action['object'])} input values for action_id: {action_id}"
        )
        logger.debug(
            f"Input values added to the action {action_id}: {action['object']}"
        )
        # Add output parameters and values
        if prov_docs.returns:
            raise NotImplementedError(
                "Adding output parameters from docstrings is not yet implemented."
            )
        else:
            logger.info(
                "No output parameters found in the constructor docstring; extracting "
                "outputs from the provenance log."
            )
        action_entry_output = prov_log.get_entries_for_key(
            key_name="output_files",
            action="/output",
            whole_entry=True,
            entry_list=action_entry_list,
        )
        multiple_output_groups = False
        if len(action_entry_output) > 1:
            multiple_output_groups = True
            logger.debug(
                f"Multiple output groups found ({len(action_entry_output)}): it is recommended "
                f"to use group labels to distinguish between output types."
            )
        for output_entry in action_entry_output:
            output_files = output_entry["output_files"]
            output_group = output_entry.get("output_group", "")
            if multiple_output_groups and not output_group:
                logger.warning(
                    "Multiple output groups found in the provenance log, but no 'output_group' "
                    "label provided for one or more outputs."
                )
            for output_file in output_files:
                output_file_name = os.path.basename(output_file)
                if output_group:
                    output_file_name = f"{output_group}::{output_file_name}"
                builder.output = {
                    "name": output_file_name,
                    "contentUrl": output_file,
                    "additionalType": "File",
                }
                output_param = builder.output
                builder.output_value = {"name": output_file_name, "value": output_file}
                output_value = builder.output_value
                output_value.append_to("exampleOfWork", {"@id": output_param["@id"]})
                logger.debug(f"Adding output parameter with @id: {output_param['@id']}")
                action.append_to("result", {"@id": output_value["@id"]})
                # workflow_crate.append_to("output", {"@id": output_param["@id"]})

    crate.root_dataset["mentions"] = [
        {"@id": builder_action["@id"]} for builder_action in builder.actions
    ]

    # Save the crate
    logger.info(f"Saving RO-Crate to: {args.output_crate_path}")
    crate.write_crate(args.output_crate_path)
    abs_output_path = os.path.abspath(args.output_crate_path)
    logger.info(f"RO-Crate generation completed successfully at: {abs_output_path}")


if __name__ == "__main__":
    main()
